//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M17_Task31
{
    using M17_Task31.VM.Obj;
    using System;
    using System.Collections.Generic;
    
    
    public partial class Buyers: Row
    {
        public int Id { get; set; }
        public string familyName { get; set; }
        public string firstName { get; set; }
        public string patronymic { get; set; }
        public string phone { get; set; }
        public string email { get; set; }


        public Buyers() 
        {
            Id = 0;
            this.familyName = "";
            this.firstName = "";
            this.patronymic = "";
            this.phone = "";
            this.email = "";
        }
        public Buyers(int id, string familyName, string firstName, string patronymic, string phone, string email)
        {
            Id = id;
            this.familyName = familyName;
            this.firstName = firstName;
            this.patronymic = patronymic;
            this.phone = phone;
            this.email = email;
        }
    }
}
