//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M17_Task31
{
    using System;
    using System.Collections.Generic;
    using M17_Task31.VM.Obj;

    public partial class Products: Row
    {
        public int Id { get; set; }
        public string goodName { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> price { get; set; }


        public Products() 
        {
            Id = 0;
            this.goodName = "";
            this.weight = 0;
            this.price = 0;
        }

        public Products(int id, string goodName, int? weight, int? price)
        {
            Id = id;
            this.goodName = goodName;
            this.weight = weight;
            this.price = price;
        }

    }
}
